/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//clients/': RouteRecordInfo<'//clients/', '/clients', Record<never, never>, Record<never, never>>,
    '//clients/[id]': RouteRecordInfo<'//clients/[id]', '/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//dashboard': RouteRecordInfo<'//dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '//inventory': RouteRecordInfo<'//inventory', '/inventory', Record<never, never>, Record<never, never>>,
    '//invoices/': RouteRecordInfo<'//invoices/', '/invoices', Record<never, never>, Record<never, never>>,
    '//invoices/[id]': RouteRecordInfo<'//invoices/[id]', '/invoices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//orders/': RouteRecordInfo<'//orders/', '/orders', Record<never, never>, Record<never, never>>,
    '//orders/[id]': RouteRecordInfo<'//orders/[id]', '/orders/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//products': RouteRecordInfo<'//products', '/products', Record<never, never>, Record<never, never>>,
    '//settings': RouteRecordInfo<'//settings', '/settings', Record<never, never>, Record<never, never>>,
    '//suppliers/': RouteRecordInfo<'//suppliers/', '/suppliers', Record<never, never>, Record<never, never>>,
    '//suppliers/[id]': RouteRecordInfo<'//suppliers/[id]', '/suppliers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
