//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::clients::Entity as Clients;
pub use super::inventory_transactions::Entity as InventoryTransactions;
pub use super::invoices::Entity as Invoices;
pub use super::order_items::Entity as OrderItems;
pub use super::orders::Entity as Orders;
pub use super::products::Entity as Products;
pub use super::quote_items::Entity as QuoteItems;
pub use super::quotes::Entity as Quotes;
pub use super::suppliers::Entity as Suppliers;
pub use super::templates::Entity as Templates;
