//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::clients::{
    self, ActiveModel as ClientActiveModel, Entity as Clients, Model as ClientModel,
};
pub use super::inventory_mouvements::{
    self, ActiveModel as InventoryMouvementActiveModel, Entity as InventoryMouvements,
    Model as InventoryMouvementModel,
};
pub use super::invoice_items::{
    self, ActiveModel as InvoiceItemActiveModel, Entity as InvoiceItems, Model as InvoiceItemModel,
};
pub use super::invoices::{
    self, ActiveModel as InvoiceActiveModel, Entity as Invoices, Model as InvoiceModel,
};
pub use super::order_items::{
    self, ActiveModel as OrderItemActiveModel, Entity as OrderItems, Model as OrderItemModel,
};
pub use super::orders::{
    self, ActiveModel as OrderActiveModel, Entity as Orders, Model as OrderModel,
};
pub use super::products::{
    self, ActiveModel as ProductActiveModel, Entity as Products, Model as ProductModel,
};
pub use super::quote_items::{
    self, ActiveModel as QuoteItemActiveModel, Entity as QuoteItems, Model as QuoteItemModel,
};
pub use super::quotes::{
    self, ActiveModel as QuoteActiveModel, Entity as Quotes, Model as QuoteModel,
};
pub use super::sellers::{
    self, ActiveModel as SellerActiveModel, Entity as Sellers, Model as SellerModel,
};
